# Generated by Django 5.1.4 on 2025-04-12 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
        ("users", "0006_remove_user_last_login_user_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="root_folder",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_root",
                to="storage.folder",
            ),
        ),
    ]
