# Generated by Django 5.1.4 on 2025-04-13 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
        ("users", "0007_alter_user_root_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_users",
                to="storage.folder",
            ),
        ),
    ]
