# Generated by Django 5.1.4 on 2025-04-13 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
        ("users", "0008_user_current_folder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="current_folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_users",
                to="storage.folder",
            ),
        ),
    ]
