# Generated by Django 5.1.4 on 2025-04-08 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="all_owned_folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to="storage.folder",
                    ),
                ),
                (
                    "users_with_editing_access",
                    models.ManyToManyField(
                        related_name="shared_editable_folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "users_with_view_access",
                    models.ManyToManyField(
                        related_name="shared_viewable_folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("telegram_id", models.BigIntegerField()),
                ("size", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("image", "Изображение"),
                            ("spreadsheet", "Электронная таблица"),
                            ("video", "Видео"),
                            ("archive", "Архив"),
                            ("document", "Текстовый документ"),
                            ("presentation", "Презентация"),
                            ("audio", "Аудио"),
                            ("code", "Исходный код"),
                            ("other", "Другой"),
                        ]
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="storage.folder",
                    ),
                ),
            ],
        ),
    ]
